import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />

        <title>Pages / Login - NiceAdmin Bootstrap Template</title>

        <link href="https://fonts.gstatic.com" rel="preconnect" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet" />

        <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
        <link href="/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" />
        <link href="/assets/vendor/quill/quill.snow.css" rel="stylesheet" />
        <link href="/assets/vendor/quill/quill.bubble.css" rel="stylesheet" />
        <link href="/assets/vendor/remixicon/remixicon.css" rel="stylesheet" />
        <link href="/assets/vendor/simple-datatables/style.css" rel="stylesheet" />

        <link href="/assets/css/style.css" rel="stylesheet" />
        <script src="/assets/vendor/apexcharts/apexcharts.min.js" async></script>
        <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js" async></script>
        <script src="/assets/vendor/chart.js/chart.umd.js" async></script>
        <script src="/assets/vendor/echarts/echarts.min.js" async></script>
        <script src="/assets/vendor/quill/quill.min.js" async></script>
        <script src="/assets/vendor/simple-datatables/simple-datatables.js" async></script>
        <script src="/assets/vendor/tinymce/tinymce.min.js" async></script>
        <script src="/assets/vendor/php-email-form/validate.js" async></script>

        {/* <script src="/assets/js/main.js" async></script> */}
      </head>
      <body className={inter.className}>
        <div>
          {children}
          <Link href="#" className="back-to-top d-flex align-items-center justify-content-center"><i className="bi bi-arrow-up-short"></i></Link>
        </div>
      </body>
    </html>
  );
}
